# Generated by Django 5.2.8 on 2025-12-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('news', 'Новости'), ('publication', 'Публикации'), ('bim', 'BIM технологии'), ('map', 'Картограмма')], max_length=20)),
                ('intro', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='posts/')),
            ],
        ),
    ]
